# Generated by Django 3.1.2 on 2020-10-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(default='topics/topic.png', upload_to='topics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
