# Generated by Django 3.1.2 on 2020-10-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='topic',
            new_name='discussion',
        ),
    ]
