# Generated by Django 3.1.2 on 2020-11-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='best_comments_order',
            field=models.BooleanField(default=False),
        ),
    ]
