# Generated by Django 3.1.2 on 2020-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20201103_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
