# Generated by Django 3.1.2 on 2020-11-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20201022_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
